services:
  app:
    build: .
    image: lucas42/lucos_docker_health_app
    container_name: lucos_docker_health_app
    restart: always
    group_add:
      - "docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["/lucos_docker_health", "--healthcheck"]
      interval: 65s
      timeout: 5s
      retries: 3
    environment:
      - SYSTEM
      - HOSTDOMAIN
      - SCHEDULE_TRACKER_ENDPOINT
