services:
  app:
    build: .
    image: lucas42/lucos_docker_health_app
    container_name: lucos_docker_health_app
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SYSTEM
      - HOSTDOMAIN
      - SCHEDULE_TRACKER_ENDPOINT
